#!/usr/bin/env python3
"""Read and validate the product and C ABI versions used by release tooling."""

from __future__ import annotations

import argparse
import json
import os
from pathlib import Path
import re
import subprocess
import sys


PROJECT_VERSION_PATTERN = re.compile(
    r"project\s*\(\s*MacinRenderADMCore\s+VERSION\s+([0-9]+\.[0-9]+\.[0-9]+)", re.DOTALL
)
API_VERSION_PATTERN = re.compile(r"^#define\s+ADM_API_VERSION_(MAJOR|MINOR|PATCH)\s+([0-9]+)\s*$", re.MULTILINE)
PROJECT_URL = "https://github.com/SakuzyPeng/MacinRender-ADM-Core"


def read_metadata(repo_root: Path) -> dict[str, str]:
    cmake_text = (repo_root / "CMakeLists.txt").read_text(encoding="utf-8")
    project_match = PROJECT_VERSION_PATTERN.search(cmake_text)
    if project_match is None:
        raise ValueError("could not read PROJECT_VERSION from CMakeLists.txt")

    header_text = (repo_root / "include/adm/c_api.h").read_text(encoding="utf-8")
    api_parts = {name.lower(): value for name, value in API_VERSION_PATTERN.findall(header_text)}
    if set(api_parts) != {"major", "minor", "patch"}:
        raise ValueError("could not read ADM_API_VERSION_* macros from include/adm/c_api.h")

    return {
        "product_version": project_match.group(1),
        "c_api_version": ".".join(api_parts[name] for name in ("major", "minor", "patch")),
        "project_url": PROJECT_URL,
    }


def git_value(repo_root: Path, *args: str) -> str | None:
    try:
        result = subprocess.run(
            ["git", "-C", str(repo_root), *args],
            check=True,
            capture_output=True,
            text=True,
        )
    except (OSError, subprocess.CalledProcessError):
        return None
    value = result.stdout.strip()
    return value or None


def normalize_release_version(value: str) -> str:
    return value[1:] if value.startswith("v") else value


def package_version(metadata: dict[str, str], repo_root: Path) -> str:
    requested = os.environ.get("MRADM_VERSION")
    if requested is None and os.environ.get("GITHUB_REF_TYPE") == "tag":
        requested = os.environ.get("GITHUB_REF_NAME")
    if requested is None:
        requested = git_value(repo_root, "describe", "--tags", "--exact-match")

    if requested is not None:
        release_version = normalize_release_version(requested)
        if release_version != metadata["product_version"]:
            raise ValueError(
                f"release version '{requested}' does not match CMake product version "
                f"'{metadata['product_version']}'"
            )
        return release_version

    short_sha = git_value(repo_root, "rev-parse", "--short=12", "HEAD") or "unknown"
    return f"{metadata['product_version']}-dev.{short_sha}"


def write_gui_build_info(path: Path, metadata: dict[str, str], repo_root: Path) -> None:
    commit = git_value(repo_root, "rev-parse", "HEAD") or "unknown"
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(
        "// <auto-generated />\n"
        "namespace MacinRender.Gui;\n\n"
        "internal static class BuildInfo\n"
        "{\n"
        f"    internal const string ProductVersion = \"{metadata['product_version']}\";\n"
        f"    internal const string ExpectedCApiVersion = \"{metadata['c_api_version']}\";\n"
        f"    internal const string Commit = \"{commit}\";\n"
        f"    internal const string ProjectUrl = \"{metadata['project_url']}\";\n"
        "}\n",
        encoding="utf-8",
    )


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--repo-root", type=Path, default=Path(__file__).resolve().parents[2])
    parser.add_argument("--field", choices=("product-version", "c-api-version", "package-version", "json"))
    parser.add_argument("--check", action="store_true")
    parser.add_argument("--tag")
    parser.add_argument("--write-gui-build-info", type=Path)
    args = parser.parse_args()

    try:
        repo_root = args.repo_root.resolve()
        metadata = read_metadata(repo_root)
        if args.tag is not None and normalize_release_version(args.tag) != metadata["product_version"]:
            raise ValueError(
                f"release tag '{args.tag}' does not match CMake product version "
                f"'{metadata['product_version']}'"
            )
        if args.write_gui_build_info is not None:
            write_gui_build_info(args.write_gui_build_info, metadata, repo_root)
        if args.field == "product-version":
            print(metadata["product_version"])
        elif args.field == "c-api-version":
            print(metadata["c_api_version"])
        elif args.field == "package-version":
            print(package_version(metadata, repo_root))
        elif args.field == "json":
            print(json.dumps(metadata, sort_keys=True))
        elif args.check:
            print(
                f"version metadata is valid: product {metadata['product_version']}, "
                f"C API {metadata['c_api_version']}"
            )
    except (OSError, ValueError) as error:
        print(f"version metadata error: {error}", file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
