include_guard(GLOBAL)
include(FetchContent)

function(mr_adm_core_json_string output value)
    string(REPLACE "\\" "\\\\" escaped "${value}")
    string(REPLACE "\"" "\\\"" escaped "${escaped}")
    string(REPLACE "\n" "\\n" escaped "${escaped}")
    string(REPLACE "\r" "\\r" escaped "${escaped}")
    string(REPLACE "\t" "\\t" escaped "${escaped}")
    set(${output} "\"${escaped}\"" PARENT_SCOPE)
endfunction()

# Record the dependencies actually resolved by MRDependencies, not every stale checkout in
# a shared cache. GetProperties also follows FETCHCONTENT_SOURCE_DIR_<NAME> overrides.
function(mr_adm_core_write_dependency_record)
    get_property(names GLOBAL PROPERTY MR_ADM_DEPENDENCY_NAMES)
    list(REMOVE_DUPLICATES names)
    list(SORT names)
    set(record "{\"version\":1,\"dependencies\":[]}")
    mr_adm_core_json_string(project_source "${CMAKE_SOURCE_DIR}")
    string(JSON record SET "${record}" project_source_dir "${project_source}")
    set(index 0)
    foreach(name IN LISTS names)
        set(content_name "${name}")
        if(name STREQUAL "tl-expected")
            set(content_name expected)
        endif()
        set(source_dir "")
        set(populated FALSE)
        FetchContent_GetProperties(${content_name} SOURCE_DIR source_dir POPULATED populated)
        if(populated AND source_dir)
            set(provider source)
        else()
            set(provider external)
            set(source_dir "")
        endif()
        get_property(target GLOBAL PROPERTY "MR_ADM_DEPENDENCY_TARGET_${name}")
        set(config_key "${name}_DIR")
        set(config_dir "")
        if(DEFINED ${config_key} AND ${config_key})
            set(config_dir "${${config_key}}")
        endif()
        set(dependency "{}")
        foreach(key IN ITEMS name target provider source_dir config_dir)
            mr_adm_core_json_string(value "${${key}}")
            string(JSON dependency SET "${dependency}" "${key}" "${value}")
        endforeach()
        string(JSON record SET "${record}" dependencies ${index} "${dependency}")
        math(EXPR index "${index} + 1")
    endforeach()
    file(WRITE "${CMAKE_BINARY_DIR}/consistency-dependencies.json" "${record}\n")
endfunction()
