[package]
name = "mradm-ffi"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[lib]
crate-type = ["staticlib", "rlib"]

[dependencies]
mradm-ear = { path = "../mradm-ear" }
mradm-wav = { path = "../mradm-wav" }
mradm-adm = { path = "../mradm-adm" }
mradm-dsp = { path = "../mradm-dsp", default-features = false }

[features]
diagnostics = ["mradm-dsp/diagnostics", "mradm-ear/diagnostics"]
default = ["sofa"]
sofa = ["mradm-dsp/sofa"]
