#!/usr/bin/env python3
"""Import immutable libear tables (Apache-2.0), never run by production builds."""
import argparse
import hashlib
import json
import math
import re
import subprocess
from pathlib import Path

parser = argparse.ArgumentParser()
parser.add_argument('source', type=Path)
a = parser.parse_args()
revision = subprocess.check_output(['git', '-C', str(a.source), 'rev-parse', 'HEAD'], text=True).strip()
if revision != '2db69f8fcea0bc5db8a78e14a9c2ae6ed4283c15':
    raise SystemExit('Expected the pinned libear commit; update provenance explicitly for an upgrade')
root = Path(__file__).resolve().parents[2]
dst = root / 'rust/crates/mradm-ear'
files = ['src/bs2051_layouts.cpp', 'src/common/facets.cpp',
         'src/direct_speakers/mapping_rules.cpp', 'resources/Design_5200_100_random.dat', 'resources/README.md', 'LICENSE']
def literal(s):
    s = re.sub(r'std::sqrt\((\d+\.\d+) / (\d+\.\d+)\)', lambda m: repr(math.sqrt(float(m[1])/float(m[2]))), s)
    s = re.sub(r'std::vector<Channel>|PolarPosition|Channel|Layout|std::make_pair', '', s)
    s = s.translate(str.maketrans('{}()', '[][]'))
    s = re.sub(r',\s*]', ']', s)
    return json.loads(s)
def initializer(s, name):
    tail = s.split(name + ' = ', 1)[1]
    return literal(tail.split(';', 1)[0])
source = (a.source / files[0]).read_text()
layouts = initializer(source, 'BS2051_LAYOUTS')
lines = ['// Preserve upstream evaluated constants, including their rounding.', '#![allow(clippy::approx_constant)]', '// Derived from EBU libear 2db69f8f (Apache-2.0). See PROVENANCE.json.',
         '// Generated by scripts/research/import-ear-data.py; order is significant.',
         'use crate::{Channel, Layout, Error, Result};',
         'pub fn layout(name: &str) -> Result<Layout> {',
         'let channels = match name {']
for name, channels in layouts:
    lines.append(f'{json.dumps(name)} => vec![')
    for label, real, nominal, az, el, lfe in channels:
        real = real + [1.0] if len(real) == 2 else real
        nominal = nominal + [1.0] if len(nominal) == 2 else nominal
        lines.append('Channel { name: %s.into(), real: %s, nominal: %s, azimuth_range: %s, elevation_range: %s, lfe: %s },' %
                     (json.dumps(label), repr(real), repr(nominal), repr(az), repr(el), str(lfe).lower()))
    lines.append('],')
lines += ['_ => return Err(Error::Unsupported("Unknown EAR layout")),', '};', 'Ok(Layout { name: name.into(), channels })', '}']
s = (a.source / files[1]).read_text()
lines += ['pub fn facets(name: &str) -> Option<Vec<Vec<usize>>> {', 'Some(match name {']
for symbol, values in re.findall(r'const std::vector<Facet> (FACETS_\w+) = (\{.*?\});', s, re.S):
    name = symbol.removeprefix('FACETS_').replace('_', '+')
    facets = literal(values)
    lines.append(json.dumps(name) + ' => vec![' + ','.join('vec!'+repr(sorted(f)) for f in facets) + '],')
lines += ['_ => return None,', '})', '}']
s = (a.source / files[2]).read_text()
lines += ['pub struct Rule { pub label: &\'static str, pub gains: &\'static [(&\'static str, f64)], pub inputs: &\'static [&\'static str], pub outputs: &\'static [&\'static str] }', 'pub const RULES: &[Rule] = &[']
for label, gains, inputs, outputs in initializer(s, 'rules'):
    lines.append('Rule { label: %s, gains: &[%s], inputs: &%s, outputs: &%s },' %
                 (json.dumps(label), ','.join('(%s,%r)' % (json.dumps(n),g) for n,g in gains), json.dumps(inputs), json.dumps(outputs)))
lines += ['];', 'pub const PACKS: &[(&str, &str)] = &[']
for pack, name in initializer(s, 'itu_packs'):
    lines.append(f'({json.dumps(pack)}, {json.dumps(name)}),')
lines += ['];']
(dst/'src/data.rs').write_text('\n'.join(lines)+'\n')
for f in files[3:]:
    (dst / ('LICENSE' if f == 'LICENSE' else 'assets/'+Path(f).name)).write_bytes((a.source/f).read_bytes())
(dst/'PROVENANCE.json').write_text(json.dumps({'upstream':'https://github.com/ebu/libear', 'commit':'2db69f8fcea0bc5db8a78e14a9c2ae6ed4283c15', 'license':'Apache-2.0', 'files':{f: hashlib.sha256((a.source/f).read_bytes()).hexdigest() for f in files}}, indent=2)+'\n')
subprocess.run(['rustfmt', '--edition', '2024', str(dst/'src/data.rs')], check=True, cwd=root/'rust')
p = dst/'PROVENANCE.json'
v = json.loads(p.read_text())
for name in ['src/common/point_source_panner.cpp', 'src/common/convex_hull.cpp', 'src/common/geom.cpp',
             'src/object_based/polar_extent.cpp', 'src/object_based/polar_extent_scalar.cpp',
             'src/direct_speakers/gain_calculator_direct_speakers.cpp', 'src/hoa/gain_calculator_hoa.cpp',
             'src/hoa/hoa.hpp', 'src/decorrelate.cpp']:
    v['files'][name] = hashlib.sha256((a.source/name).read_bytes()).hexdigest()
v['assets'] = {name: hashlib.sha256((dst/name).read_bytes()).hexdigest()
               for name in ['assets/Design_5200_100_random.dat', 'assets/README.md', 'src/data.rs']}
p.write_text(json.dumps(v, indent=2)+'\n')
print(f'Imported {len(layouts)} layouts and immutable EAR data')
